// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyeptukwcplcvjjupmfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5ZXB0dWt3Y3BsY3ZqanVwbWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzgwMTYsImV4cCI6MjA2MDQxNDAxNn0.R2HY6E3oprK3Rqa576h5bygWUYK3IL5MRgruIUKGpTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);